### PR TITLE
Separate KubeVirt and CDI from dco-core as sub-packages

### PR DESCRIPTION
**Pull request by mikevanhemert**
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Description

Currently, KubeVirt and CDI are part of the `dco-core` monolith. This change creates a new composable Zarf package called `kubevirt` that contains the KubeVirt and CDI components and links them to the `dco-core` parent Zarf package.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Local deployment
- [ ] Pipeline deployment

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have added a plain language explanation of the changes to the Unreleased section of the CHANGELOG.md file

### CODE REVIEW

**Review by docandrew — APPROVED** [review]
👍

**Comment by bburky** [comment]
Not quite sure if this was ready for review, it sounded like it was? You'll want to edit the `path:` in the Kustomizations in `kubevirt/manifests/` to point to the new path

**Comment by bburky** [comment]
Also, the dco-core workflow `.github/workflows/dco-core.yaml` needs to include `kubevirt/**` in `on.push.paths now.

**Review by benmountjoy111 — APPROVED** [review]
❤️

**Review by docandrew — APPROVED** [review]
👍

**Pull request merged**
